# Specify environmental parameters including MySQL database domain (%), database name, password, terminal, and file save locations.
# Port: Ports? Communication is impossible without connecting - Spring port is 8080; MySQL port is 3306.
# This YML file specifies the infrastructure inside Docker and tells it how to run.
# Docker is a virtual machine.
version: '3.8'

services:
  db:     #Created a database server => This server has software called MySQL. MySQL can run different databases. (If other projects in our portfolio also use MySQL, we can use this server to run them. Each database has its own name defined by the MYSQL_DATABASE field.)
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: secret
      TZ: UTC
    volumes:
      - mysql-local:/var/lib/mysql
    ports:
      - 3306:3306

# permanent storage of data.
volumes:
  mysql-local: